######################### Proxies.sx OFFICIAL MASTER #########################
# API Key lấy từ https://farmer.proxies.sx/
PROXIES_SX_API_KEY=""

# Tiền tố tên thiết bị trên Dashboard
DEVICE_NAME="ubuntu"

# Độ trễ khởi tạo giữa các node (giây) - chống rate-limit HTTP 429
DELAY_BETWEEN_CONTAINER=2